Full-Stack-MVC-master/Full-Stack-MVC-master/Models/Instructor.cs
using FullstackMVC.Validators;
using mvcLab.Validators;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace mvcLab.Models
{
    public class Instructor
    {
        public int Id { get; set; }
        
        public string Name { get; set; }
        public string Address { get; set; }
        [Required(ErrorMessage = "Degree is required.")]
        [Range(20,40,ErrorMessage ="age must be between 20-40")]
        public int Age { get; set; }
        [Required(ErrorMessage = "salary is required.")]
        [SalaryValidator]
        public decimal Salary { get; set; }
        [Required(ErrorMessage = "Degree is required.")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Please enter a degree between (2,20) characters.")]
        public string Degree { get; set; }
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]
        [UniqueEmail]
        public string Email { get; set; }

        [ForeignKey(nameof(Department))]
        public int? DepartmentId { get; set; }
        public Department? Department { get; set; }

 

        public ICollection<InstructorCourse>? InstructorCourses { get; set; }

    }
}

Full-Stack-MVC-master/Full-Stack-MVC-master/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvcLab.Models;

namespace mvcLab.Controllers
{
    public class InstructorController : Controller
    {
        private ApplicationDbContext context;
        public InstructorController(ApplicationDbContext _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            List<Instructor> instructors = context.Instructors.Include(d => d.Department).Include(e=>e.InstructorCourses).ThenInclude(e=>e.Course).ToList();
            return View(instructors);
        }
        [Authorize(Roles = "Admin")]

        public IActionResult Create()
        {
            ViewBag.Departments = context.Departments.ToList();
            ViewBag.Courses = context.Courses.ToList();
            return View();

        }
        [HttpPost]
        [Authorize(Roles = "Admin")]

        public IActionResult Create(Instructor instructor, List<int> SelectedCourseIds)
        {
            if (ModelState.IsValid)
            {
                instructor.InstructorCourses = new List<InstructorCourse>();

                foreach (var courseId in SelectedCourseIds)
                {
                    instructor.InstructorCourses.Add(new InstructorCourse
                    {
                        CourseId = courseId,

                    });
                }
                context.Instructors.Add(instructor);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Departments = context.Departments.ToList();
            ViewBag.Courses = context.Courses.ToList();
            return View();
        }
        [Authorize(Roles = "Admin")]

        public IActionResult Edit()
        {
            ViewBag.Departments = context.Departments.ToList();
            ViewBag.Courses = context.Courses.ToList();
            return View();

        }
        [HttpPost]
        [Authorize(Roles = "Admin")]

        public IActionResult Edit(Instructor instructor, List<int> SelectedCourseIds)
        {
            if (SelectedCourseIds == null)
            {
                throw new Exception("must select courses");
            }
            if (ModelState.IsValid)
            {
                var myInstructor = context.Instructors.Include(s => s.InstructorCourses).FirstOrDefault(i => i.Id == instructor.Id);
                if (myInstructor.InstructorCourses != null)
                {
                    myInstructor.InstructorCourses.Clear();
                }
                myInstructor.Name = instructor.Name;
                myInstructor.Address = instructor.Address;
                myInstructor.Salary = instructor.Salary;
                myInstructor.Age = instructor.Age;
                myInstructor.Degree = instructor.Degree;
                myInstructor.Email = instructor.Email;
                myInstructor.InstructorCourses = new List<InstructorCourse>();
                foreach (var courseId in SelectedCourseIds)
                {
                    myInstructor.InstructorCourses.Add(new InstructorCourse
                    {
                        CourseId = courseId,

                    });
                }
                context.Instructors.Update(myInstructor);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Departments = context.Departments.ToList();
            ViewBag.Courses = context.Courses.ToList();

            return View(instructor);
        }
    }
}

Full-Stack-MVC-master/Full-Stack-MVC-master/Views/Instructor/Create.cshtml
@model Instructor
@{
    SelectList depts = new SelectList(ViewBag.Departments, "Id", "Name");
}

<div class="container-fluid px-1 py-5 mx-auto">
    <div class="row d-flex justify-content-center">
        <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
            <h3>Create Instructor</h3>
            <p class="blue-text">Fill the form below to register a new Instructor</p>

            <div class="card p-4">
                <h5 class="text-center mb-4">Instructor Information</h5>

                <form asp-action="Create" asp-controller="Instructor" method="post" class="form-card">

                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Name">Name<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Name" placeholder="Enter Instructor name" />
                            <span class="text-danger" asp-validation-for="Name"></span>
                        </div>

                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Age">Age<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Age" placeholder="Enter Age" />
                            <span class="text-danger" asp-validation-for="Age"></span>
                        </div>
                    </div>

                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-12 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Email">Email<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Email" placeholder="Enter Email" />
                            <span class="text-danger" asp-validation-for="Email"></span>
                        </div>
                    </div> <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-12 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Address">Address<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Address" placeholder="Enter Address" />
                            <span class="text-danger" asp-validation-for="Address"></span>
                        </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <select asp-for="DepartmentId" asp-items="@depts" class="form-control m-1">
                            <option value="0">----Select Department----</option>
                      </select>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-12 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Salary">Salary<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Salary" placeholder="Enter Salary" />
                            <span class="text-danger" asp-validation-for="Salary"></span>
                        </div>
                 
                    </div><div class="row justify-content-between text-left">
                        <div class="form-group col-sm-12 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Degree">Degree<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Degree" placeholder="Enter Degree" />
                            <span class="text-danger" asp-validation-for="Degree"></span>
                        </div>
                    </div>

                    <div class="row justify-content-between text-left">
                        <table>
                            <tbody>
                                @foreach (var c in ViewBag.Courses)
                                {
                                    <tr>
                                        <td class="form-floating form-control-color">

                                            <input type="checkbox" name="SelectedCourseIds" value="@c.Num" id="Course_@c.Num" />
                                            <label for="Course_@c.Num" class="ms-2">@c.Name</label>
                                        </td>
                                    </tr>
                                }
                            </tbody>

                        </table>

                    </div>



                    <hr class="my-4" />


                    <div class="row justify-content-end mt-4">
                        <div class="form-group col-sm-6">
                            <button type="submit" class="btn btn-block btn-primary">Create Instructor</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>

Full-Stack-MVC-master/Full-Stack-MVC-master/Views/Instructor/Edit.cshtml
@model Instructor
@{
    SelectList depts = new SelectList(ViewBag.Departments, "Id", "Name");
}

<div class="container-fluid px-1 py-5 mx-auto">
    <div class="row d-flex justify-content-center">
        <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
            <h3>Create Instructor</h3>
            <p class="blue-text">Fill the form below to register a new Instructor</p>

            <div class="card p-4">
                <h5 class="text-center mb-4">Instructor Information</h5>

                <form asp-action="Edit" asp-controller="Instructor" method="post" class="form-card">

                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Name">Name<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Name" placeholder="Enter Instructor name" />
                            <span class="text-danger" asp-validation-for="Name"></span>
                        </div>

                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Age">Age<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Age" placeholder="Enter Age" />
                            <span class="text-danger" asp-validation-for="Age"></span>
                        </div>
                    </div>

                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-12 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Email">Email<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Email" placeholder="Enter Email" />
                            <span class="text-danger" asp-validation-for="Email"></span>
                        </div>
                    </div> <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-12 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Address">Address<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Address" placeholder="Enter Address" />
                            <span class="text-danger" asp-validation-for="Address"></span>
                        </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <select asp-for="DepartmentId" asp-items="@depts" class="form-control m-1">
                            <option value="0">----Select Department----</option>
                        </select>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-12 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Salary">Salary<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Salary" placeholder="Enter Salary" />
                            <span class="text-danger" asp-validation-for="Salary"></span>
                        </div>

                    </div><div class="row justify-content-between text-left">
                        <div class="form-group col-sm-12 flex-column d-flex">
                            <label class="form-control-label px-3" asp-for="Degree">Degree<span class="text-danger"> *</span></label>
                            <input class="form-control" asp-for="Degree" placeholder="Enter Degree" />
                            <span class="text-danger" asp-validation-for="Degree"></span>
                        </div>
                    </div>

                    <div class="row justify-content-between text-left">
                        <table>
                            <tbody>
                                @foreach (var c in ViewBag.Courses)
                                {
                                    <tr>
                                        <td class="form-floating form-control-color">

                                            <input type="checkbox" name="SelectedCourseIds" value="@c.Num" id="Course_@c.Num" />
                                            <label for="Course_@c.Num" class="ms-2">@c.Name</label>
                                        </td>
                                    </tr>
                                }
                            </tbody>

                        </table>

                    </div>



                    <hr class="my-4" />


                    <div class="row justify-content-end mt-4">
                        <div class="form-group col-sm-6">
                            <button type="submit" class="btn btn-block btn-primary">Edit Instructor</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>

Full-Stack-MVC-master/Full-Stack-MVC-master/Views/Instructor/Index.cshtml
@model List<Instructor>

<div class="container mt-5">
    <div class="row mb-3">
        <div class="col-12">
            <h1 class="text-center text-primary"> Instructor List</h1>
        </div>
         @if (User.IsInRole("Admin"))
                            {
        <td class="text-center btn btn-info">
            <a asp-action="Create"
               asp-controller="Instructor">
                Create <i class="bi bi-arrow-right-short"></i>
            </a>
        </td>
                            }
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered align-middle">
            <thead class="table-dark">
                <tr>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Salary</th>
                    <th>Department</th>
                    <th>Courses Enrolled</th>
                    <th>Actions</th>
                    <th>Actions</th>
                            @if (User.IsInRole("Admin"))
                            {
                    <th>Actions</th>
                    <th>Actions</th>
                            }
                </tr>
            </thead>
            <tbody class="table-group-divider">
                @if (Model.Any())
                {
                    @foreach (var ins in Model)
                    {
                        <tr>
                            <td>
                                <div class="d-flex align-items-center">
                                   
                                    <strong>@ins.Name</strong>
                                </div>
                            </td>

                            <td class="text-center">@ins.Age</td>

                            <td>@ins.Salary</td>

                            <td>@ins.Department.Name</td>

                            <td>
                                <div class="d-flex flex-wrap gap-2">
                                    @foreach (var course in ins.InstructorCourses)
                                    {
                                        <span class="badge bg-info text-dark fw-normal">@course.Course.Name</span>
                                    }
                                    @if (ins.InstructorCourses.Count > 3)
                                    {
                                        <span class="badge bg-secondary text-white opacity-75" title="@(ins.InstructorCourses.Count - 3) more courses">
                                            +@(ins.InstructorCourses.Count - 3)
                                        </span>
                                    }
                                </div>
                            </td>

                            <td class="text-center">
                                <a asp-action="Details"
                                   asp-controller="Instructor"
                                   asp-route-id="@ins.Id">
                                    Details <i class="bi bi-arrow-right-short"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a asp-action="DetailsVM"
                                   asp-controller="Instructor"
                                   asp-route-id="@ins.Id">
                                    DetailsVM <i class="bi bi-arrow-right-short"></i>
                                </a>
                            </td>
        @if (User.IsInRole("Admin"))
                            {
                                <td class="text-center">
                                    <a asp-action="Edit"
                                    asp-controller="Instructor"
                                    asp-route-id="@ins.Id">
                                        Edit <i class="bi bi-arrow-right-short"></i>
                                    </a>
                                </td>
                                <td class="text-center bg-danger">
                                    <a asp-action="Delete"
                                    asp-controller="Instructor"
                                    asp-route-id="@ins.Id">
                                        Delete <i class="bi bi-arrow-right-short"></i>
                                    </a>
                                </td>
                            }
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="6" class="text-center text-danger py-4">
                            <i class="bi bi-exclamation-triangle-fill me-2"></i> No Instructor records are currently available.
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>